### ISSUE TITLE
Correction to the lesson content

### ISSUE THREAD

**Issue by JJJV** [learn-co-curriculum/swift-math-readme#8]
Minor corrections to the content, in the final portion of the lesson:

Most functions return some kind of value; either something which is retrieved, computed, or just a code indicating success or failure. For example, here's a function which returns the average of two "Doubles":

It should read "Ints".

And further below:

You can also have a function which returns the average of three "Ints":

Should read "Doubles"

**Comment by JimCampagno** [comment]
@JJJV Thanks for pointing that out, I appreciate it!

I just made the necessary changes.
